# Generated by Django 3.1.3 on 2020-12-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.TextField()),
                ('price', models.CharField(max_length=15)),
                ('url', models.URLField()),
            ],
        ),
    ]
